### ISSUE TITLE
ユーザー登録でなぜメールアドレスが必要か

### ISSUE THREAD

**Issue by Aseiide** [Aseiide/cafe-map#5]
# 大体の流れ
多くのwebサイトでは以下のような手順が取られている
1 : 新規登録画面でメールアドレスの入力を要求
↓
2 : そのメールアドレスに対して本登録用のリンクを記載したメールを送信
↓
3 : リンクから遷移した先のフォームに必要事項を記入
今回の場合は、IDとパスワードとemailを入力
↓
4 : 登録完了

# なぜemailを使った認証が必要なのか？
## 不正登録を防ぐ
もし、メール受信なくユーザー登録が完了してしまった場合、無限にアカウントが作れてしまう。
その場合、不正に利用されてしまう可能性があるので手順を複雑化し、不正利用を防ぐのが狙い。

## メールアドレスが有効か確認する
ユーザーとの連絡手段を確立するため。
もし、入力されたメールアドレスが間違っていた場合、ユーザーとの連絡が確立できず「ユーザー登録が完了した」事すらも伝えることができない。
よって、メールアドレスが正常に受信できるかどうか確認している

# Railsでの認証
~~Railsでログイン認証をするにはdeviseというgemを使って実装するみたい。~~

~~[[*Rails*] deviseの使い方（rails5版）](https://qiita.com/cigalecigales/items/f4274088f20832252374)~~

Railsチュートリアル
パスワードとかメールアドレスに一通りの処理（一意性、有効性などなど）をした上で```log_in```メソッドとか```has_secure_password```を使うみたい。

https://railstutorial.jp/chapters/sign_up?version=5.1#toc

## gemによる認証方法
- devise
- socery
どちらも簡単にユーザー認証を実装できるライブラリ

## なぜgemを使わないのか？
調べたが、わからんかった。
「最初だし、エンジニアとして認証自作したほうがよいのかな〜。」という理解

[A tip for newcommers](https://github.com/heartcombo/devise/commit/5f93d8355)
[画像参照元](https://diary.app.ssig33.com/491)

![スクリーンショット 2020-11-04 22 06 53](https://user-images.githubusercontent.com/45246171/98115437-2bbe3b80-1eea-11eb-9a43-3fee2328726b.png)

**Comment by kos31de** [comment]
> Railsでログイン認証をするにはdeviseというgemを使って実装するみたい。

Railsチュートリアルではdevise使ってたっけ？
初めはチュートリアルのやり方に則って欲しい。
deviseは便利なgemだけど、実務では使わないこともよくあるので。
ほかにもsorceryとかあったりする。

**Comment by Aseiide** [comment]
> deviseは便利なgemだけど、実務では使わないこともよくある

deviseがデファクトスタンダードになってる、という認識なんだけどgemを使わないってことは毎回認証自作してるってこと？

**Comment by kos31de** [comment]
全くデファクトスタンダードではないです。
自作するよ。
