### ISSUE TITLE
Railsでプルダウンを実装する方法について/enum

### ISSUE THREAD

**Issue by Aseiide** [Aseiide/cafe-map#6]
Aseiide/ide_family#96 の続き
# コメント
> これstrのカラム1つでプルダウン実現出来る？
プルダウンにするってことは、選択肢を1つずつデータ持ってることが一般的です。
例えば3択でホット(0), アイス(1), その他(2)とかにして、それぞれの店舗がこれを0個以上持つとして、どういうテーブル構造にすればいいかな？
第一正規形を満たしているものとして、考えてみて欲しい。
ついでにRailsのenumとかも調べると良いよ。

# 別にメニューテーブルを用意する？
1つのカラムには1つのデータを保存。
登録したいのは、複数ある（ドリップ,エスプレッソ,ラテ）
第一正規形を満たすためには、別のテーブルを用意してそこに保存しないと行けない気がする。
イメージ↓
![PXL_20201106_110210445](https://user-images.githubusercontent.com/45246171/98359361-70bdab80-206b-11eb-945f-50ff08ca0c94.jpg)

# プルダウンのデータ構造
普段から何気なくプルダウンメニュー使っているので↑の指摘のように書く選択肢がデータベースと紐付いてるということを知らなかった。

# Railsのenumについて

enum "列挙"型
カラム名と定義対照（内容）を決めることができる。

https://qiita.com/ozackiee/items/17b91e26fad58e147f2e
https://qiita.com/clbcl226/items/3e832603060282ddb4fd

ちょっと調べる、考えるのに時間かかりそうなので明日に回す。

**Comment by kos31de** [comment]
要は
- DB側: typeみたいなカラムを持っていてホットなら0、アイスなら1、その他なら2という値を保存するようにする
- Application側: `0: hot, 1: ice, other: 2`みたいに定義して、コードの中で0を参照するときは`:hot`みたいにして参照できる

って感じだね

**Comment by Aseiide** [comment]
頭がこんがらがってきた。以下、自分の認識

**application側**
enumを使って0:drip, 1:espresso, 2:latte
と定義しておく

**DB側**
別のテーブルを用意してdripなら0,espresoなら1、latteなら2という風に数字で保存する

**Comment by kos31de** [comment]
別のテーブルを用意、で正解！

**Comment by Aseiide** [comment]
Menusテーブルにはidちtypeがintである感じかなぁと。ちょっと見づらいかも
![PXL_20201107_062929866](https://user-images.githubusercontent.com/45246171/98433956-b0899f00-210e-11eb-8a72-7fd6cc4c3afd.jpg)
